<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\angnet.Infrastructure\angnet.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <Using Include="Microsoft.Extensions.Logging" />
    <Compile Include="..\..\src\angnet.WebApi\Authorization Policy\PermissionPolicyProvider.cs" Link="Support\PermissionPolicyProvider.cs" />
    <Compile Include="..\..\src\angnet.WebApi\Controllers\ShiftReportController.cs" Link="Support\ShiftReportController.cs" />
    <Compile Include="..\..\src\angnet.WebApi\Controllers\RevenueReportController.cs" Link="Support\RevenueReportController.cs" />
    <Compile Include="..\..\src\angnet.WebApi\Authorization Policy\PermissionHandler.cs" Link="Support\PermissionHandler.cs" />
    <Compile Include="..\..\src\angnet.WebApi\Controllers\MovieWishlistController.cs" Link="Support\MovieWishlistController.cs" />
    <Compile Include="..\..\src\angnet.WebApi\Controllers\AdminAccountsController.cs" Link="Support\AdminAccountsController.cs" />
    <Compile Include="..\..\src\angnet.WebApi\Controllers\AccountController.cs" Link="Support\AccountController.cs" />
  </ItemGroup>

</Project>
