-- 0001_Baseline.sql
-- Schema goc, sinh tu EF migration 20251103151147 truoc khi bo EF Migrations.
-- Toan bo lenh deu IF NOT EXISTS nen chay an toan tren ca DB rong lan DB da co san.
-- Tu 0002 tro di: viet SQL tay, KHONG dung IF NOT EXISTS (moi script chi chay dung 1 lan).
-- Transaction do DbUp quan ly (WithTransactionPerScript).

CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" text NOT NULL,
    "TenantId" integer NOT NULL,
    "FullName" text NOT NULL,
    "Avatar" text NOT NULL,
    "Address" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AuditTrail" (
    "AuditTrailId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RecordId" text NOT NULL,
    "IPAddress" text NOT NULL,
    "Level" text NOT NULL,
    "RequestUrl" text NOT NULL,
    "TrailType" text NOT NULL,
    "Description" text NOT NULL,
    "ChangedColumns" text NOT NULL,
    "OldValues" text NOT NULL,
    "NewValues" text NOT NULL,
    "ChangedBy" text NOT NULL,
    "ChangedDTime" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    CONSTRAINT "PK_AuditTrail" PRIMARY KEY ("AuditTrailId")
);

CREATE TABLE IF NOT EXISTS "Chat" (
    "MessageId" text NOT NULL,
    "UserId" text NOT NULL,
    "Type" text NOT NULL,
    "Message" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Chat" PRIMARY KEY ("MessageId")
);

CREATE TABLE IF NOT EXISTS "GenerationAuthCode" (
    "Id" text NOT NULL,
    "Token" text NOT NULL,
    "Salt" text NOT NULL,
    "AttemptCount" integer NOT NULL,
    "Type" text NOT NULL,
    "UserId" text NOT NULL,
    "ExpiredAt" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GenerationAuthCode" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "MstPaymentType" (
    "PaymentTypeCode" text NOT NULL,
    "PaymentTypeName" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstPaymentType" PRIMARY KEY ("PaymentTypeCode")
);

CREATE TABLE IF NOT EXISTS "MstProvince" (
    "ProvinceCode" character varying(10) NOT NULL,
    "ProvinceName" text NOT NULL,
    "TenantId" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstProvince" PRIMARY KEY ("ProvinceCode")
);

CREATE TABLE IF NOT EXISTS "MstStadiumStatus" (
    "StadiumStatusCode" text NOT NULL,
    "StadiumStatusName" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstStadiumStatus" PRIMARY KEY ("StadiumStatusCode")
);

CREATE TABLE IF NOT EXISTS "MstStadiumType" (
    "StadiumTypeCode" text NOT NULL,
    "StadiumTypeName" text NOT NULL,
    "StadiumTypeSalePercent" numeric NOT NULL,
    "Remark" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstStadiumType" PRIMARY KEY ("StadiumTypeCode")
);

CREATE TABLE IF NOT EXISTS "NewsCategory" (
    "NewsCategoryId" text NOT NULL,
    "TenantId" text NOT NULL,
    "NewsCategoryParentId" text NOT NULL,
    "NewsCategoryName" text NOT NULL,
    "NewsCategoryIndex" integer NOT NULL,
    "IsGlobal" boolean NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NewsCategory" PRIMARY KEY ("NewsCategoryId")
);

CREATE TABLE IF NOT EXISTS "ShiftReport" (
    id integer GENERATED ALWAYS AS IDENTITY,
    "ShiftDate" date NOT NULL,
    "ShiftType" character varying(50) NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "ReceptionistName" character varying(100) NOT NULL,
    "TotalCash" numeric(18,2) NOT NULL DEFAULT 0.0,
    "TotalTransfer" numeric(18,2) NOT NULL DEFAULT 0.0,
    "TotalExpense" numeric(18,2) NOT NULL DEFAULT 0.0,
    "HandoverAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
    "ReceiverName" character varying(200) NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ShiftReport" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Tenant" (
    "TenantId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantCode" text NOT NULL,
    "TenantName" text NOT NULL,
    "OwnedBy" text NOT NULL,
    "TenantPrefixHost" text NOT NULL,
    "TenantHost" text NOT NULL,
    "TenantConnectionString" text NOT NULL,
    "TenantDatabaseName" text NOT NULL,
    "TenantLogo" text NOT NULL,
    "TenantDescription" text NOT NULL,
    "TenantAddress" jsonb NOT NULL,
    "TenantStatus" varchar(20) NOT NULL,
    "Remark" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tenant" PRIMARY KEY ("TenantId")
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "RefreshToken" (
    "RefreshToken" text NOT NULL,
    "TenantId" text NOT NULL,
    "UserId" text NOT NULL,
    "ExpiryDate" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("RefreshToken"),
    CONSTRAINT "FK_RefreshToken_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "MstDistrict" (
    "DistrictCode" text NOT NULL,
    "ProvinceCode" character varying(10) NOT NULL,
    "DistrictName" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstDistrict" PRIMARY KEY ("DistrictCode"),
    CONSTRAINT "FK_MstDistrict_MstProvince_ProvinceCode" FOREIGN KEY ("ProvinceCode") REFERENCES "MstProvince" ("ProvinceCode") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "News" (
    "NewsId" text NOT NULL,
    "UserId" text NOT NULL,
    "CategoryNewsId" text NOT NULL,
    "Slug" text NOT NULL,
    "Thumbnail" text NOT NULL,
    "ShortTitle" text NOT NULL,
    "ShortDescription" text NOT NULL,
    "ContentBody" text NOT NULL,
    "ViewCount" integer NOT NULL,
    "ShareCount" integer NOT NULL,
    "LikeCount" integer NOT NULL,
    "AvgPoint" double precision NOT NULL,
    "WhoCanSee" varchar(20) NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_News" PRIMARY KEY ("NewsId"),
    CONSTRAINT "FK_News_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_News_NewsCategory_CategoryNewsId" FOREIGN KEY ("CategoryNewsId") REFERENCES "NewsCategory" ("NewsCategoryId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ShiftReportRoomSale" (
    "Id" integer GENERATED ALWAYS AS IDENTITY,
    "ShiftReportId" integer NOT NULL,
    "RoomNumber" character varying(20) NOT NULL,
    "RoomCategory" character varying(50) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ShiftReportRoomSale" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ShiftReportRoomSale_ShiftReport_ShiftReportId" FOREIGN KEY ("ShiftReportId") REFERENCES "ShiftReport" (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ShiftReportTransaction" (
    "Id" integer GENERATED ALWAYS AS IDENTITY,
    "ShiftReportId" integer NOT NULL,
    "OrderNumber" integer NOT NULL,
    "RoomNumber" character varying(20) NOT NULL,
    "InvoiceCode" character varying(50) NOT NULL,
    "CustomerType" character varying(50) NOT NULL,
    "CashAmount" numeric(18,2),
    "TransferAmount" numeric(18,2),
    "PrepaidNote" character varying(200) NOT NULL,
    "ExpenseDescription" character varying(500) NOT NULL,
    "ExpenseAmount" numeric(18,2),
    "IsUseExpenseForReportRevenue" boolean NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ShiftReportTransaction" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ShiftReportTransaction_ShiftReport_ShiftReportId" FOREIGN KEY ("ShiftReportId") REFERENCES "ShiftReport" (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MstTenantContact" (
    "TenantContactId" text NOT NULL,
    "TenantId" integer NOT NULL,
    "TenantContactName" varchar(20) NOT NULL,
    "TenantContactValue" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstTenantContact" PRIMARY KEY ("TenantContactId"),
    CONSTRAINT "FK_MstTenantContact_Tenant_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenant" ("TenantId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MstStadium" (
    "StadiumCode" character varying(250) NOT NULL,
    "StadiumTypeCode" text NOT NULL,
    "StadiumStatusCode" text NOT NULL,
    "DistrictCode" text NOT NULL,
    "TenantId" text NOT NULL,
    "FlagStadiumRent" boolean NOT NULL,
    "StadiumName" text NOT NULL,
    "StadiumPrice" numeric NOT NULL,
    "StadiumDescription" text NOT NULL,
    "StadiumAddress" text NOT NULL,
    "StadiumSalePercent" numeric NOT NULL,
    "Remark" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstStadium" PRIMARY KEY ("StadiumCode"),
    CONSTRAINT "FK_MstStadium_MstDistrict_DistrictCode" FOREIGN KEY ("DistrictCode") REFERENCES "MstDistrict" ("DistrictCode") ON DELETE CASCADE,
    CONSTRAINT "FK_MstStadium_MstStadiumStatus_StadiumStatusCode" FOREIGN KEY ("StadiumStatusCode") REFERENCES "MstStadiumStatus" ("StadiumStatusCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_MstStadium_MstStadiumType_StadiumTypeCode" FOREIGN KEY ("StadiumTypeCode") REFERENCES "MstStadiumType" ("StadiumTypeCode") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "HashTagNews" (
    "HashTagNewsId" text NOT NULL,
    "NewsId" text NOT NULL,
    "HashTagNewsName" character varying(30) NOT NULL,
    "Count" integer NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HashTagNews" PRIMARY KEY ("HashTagNewsId", "NewsId"),
    CONSTRAINT "FK_HashTagNews_News_NewsId" FOREIGN KEY ("NewsId") REFERENCES "News" ("NewsId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "LikeNews" (
    "LikeNewsId" text NOT NULL,
    "NewsId" text NOT NULL,
    "UserId" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LikeNews" PRIMARY KEY ("LikeNewsId"),
    CONSTRAINT "FK_LikeNews_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LikeNews_News_NewsId" FOREIGN KEY ("NewsId") REFERENCES "News" ("NewsId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "NewsComment" (
    "CommentId" text NOT NULL,
    "NewsId" text NOT NULL,
    "UserId" text NOT NULL,
    "ParentCommentId" text,
    "Content" text NOT NULL,
    "ReplyCount" integer NOT NULL,
    "ReactionCount" integer NOT NULL,
    "Status" varchar(20) NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NewsComment" PRIMARY KEY ("CommentId"),
    CONSTRAINT "FK_NewsComment_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_NewsComment_NewsComment_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "NewsComment" ("CommentId") ON DELETE CASCADE,
    CONSTRAINT "FK_NewsComment_News_NewsId" FOREIGN KEY ("NewsId") REFERENCES "News" ("NewsId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "PointNews" (
    "NewsId" text NOT NULL,
    "UserId" text NOT NULL,
    "Point" double precision NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PointNews" PRIMARY KEY ("NewsId", "UserId"),
    CONSTRAINT "FK_PointNews_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PointNews_News_NewsId" FOREIGN KEY ("NewsId") REFERENCES "News" ("NewsId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "RefFileNews" (
    "RefFileNewsId" text NOT NULL,
    "NewsId" text NOT NULL,
    "FileUrl" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefFileNews" PRIMARY KEY ("RefFileNewsId"),
    CONSTRAINT "FK_RefFileNews_News_NewsId" FOREIGN KEY ("NewsId") REFERENCES "News" ("NewsId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MstStadiumFileModel" (
    "StadiumFileId" text NOT NULL,
    "StadiumCode" character varying(250) NOT NULL,
    "FileUrl" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstStadiumFileModel" PRIMARY KEY ("StadiumFileId"),
    CONSTRAINT "FK_MstStadiumFileModel_MstStadium_StadiumCode" FOREIGN KEY ("StadiumCode") REFERENCES "MstStadium" ("StadiumCode") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "OrderStadium" (
    "OrderStadiumId" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderStadiumCode" text NOT NULL,
    "StadiumCode" character varying(250) NOT NULL,
    "UserId" text NOT NULL,
    "OderDTime" timestamp with time zone NOT NULL,
    "RentDTimeFrom" timestamp with time zone NOT NULL,
    "RentDTimeTo" timestamp with time zone NOT NULL,
    "PaymentTypeCode" text NOT NULL,
    "PreMoney" numeric NOT NULL,
    "RefundMoney" numeric NOT NULL,
    "VAT" numeric NOT NULL,
    "SalePercent" numeric NOT NULL,
    "DebtMoney" numeric NOT NULL,
    "Remark" text NOT NULL,
    "OrderStatus" varchar(20) NOT NULL,
    "VoucherCode" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OrderStadium" PRIMARY KEY ("OrderStadiumId"),
    CONSTRAINT "FK_OrderStadium_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderStadium_MstPaymentType_PaymentTypeCode" FOREIGN KEY ("PaymentTypeCode") REFERENCES "MstPaymentType" ("PaymentTypeCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderStadium_MstStadium_StadiumCode" FOREIGN KEY ("StadiumCode") REFERENCES "MstStadium" ("StadiumCode") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "NewsCommentMedia" (
    "MediaId" text NOT NULL,
    "CommentId" text NOT NULL,
    "Url" text NOT NULL,
    "MediaType" varchar(20) NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NewsCommentMedia" PRIMARY KEY ("MediaId"),
    CONSTRAINT "FK_NewsCommentMedia_NewsComment_CommentId" FOREIGN KEY ("CommentId") REFERENCES "NewsComment" ("CommentId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "NewsCommentReaction" (
    "CommentId" text NOT NULL,
    "UserId" text NOT NULL,
    "ReactionType" varchar(20) NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NewsCommentReaction" PRIMARY KEY ("CommentId", "UserId"),
    CONSTRAINT "FK_NewsCommentReaction_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_NewsCommentReaction_NewsComment_CommentId" FOREIGN KEY ("CommentId") REFERENCES "NewsComment" ("CommentId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "NewsReportComment" (
    "ReportId" text NOT NULL,
    "CommentId" text NOT NULL,
    "UserId" text NOT NULL,
    "Reason" varchar(50) NOT NULL,
    "Description" text NOT NULL,
    "Status" varchar(20) NOT NULL,
    CONSTRAINT "PK_NewsReportComment" PRIMARY KEY ("ReportId"),
    CONSTRAINT "FK_NewsReportComment_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_NewsReportComment_NewsComment_CommentId" FOREIGN KEY ("CommentId") REFERENCES "NewsComment" ("CommentId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "OrderStadiumStatusLogModel" (
    "OrderStadiumStatusLogId" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderStadiumId" integer NOT NULL,
    "UserId" text NOT NULL,
    "PreviousStatus" text NOT NULL,
    "Status" text NOT NULL,
    "ChangedData" text NOT NULL,
    "Note" text NOT NULL,
    "IpAddress" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OrderStadiumStatusLogModel" PRIMARY KEY ("OrderStadiumStatusLogId"),
    CONSTRAINT "FK_OrderStadiumStatusLogModel_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderStadiumStatusLogModel_OrderStadium_OrderStadiumId" FOREIGN KEY ("OrderStadiumId") REFERENCES "OrderStadium" ("OrderStadiumId") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX IF NOT EXISTS "IX_HashTagNews_NewsId" ON "HashTagNews" ("NewsId");

CREATE INDEX IF NOT EXISTS "IX_LikeNews_NewsId" ON "LikeNews" ("NewsId");

CREATE INDEX IF NOT EXISTS "IX_LikeNews_UserId" ON "LikeNews" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_MstDistrict_ProvinceCode" ON "MstDistrict" ("ProvinceCode");

CREATE INDEX IF NOT EXISTS "IX_MstStadium_DistrictCode" ON "MstStadium" ("DistrictCode");

CREATE INDEX IF NOT EXISTS "IX_MstStadium_StadiumStatusCode" ON "MstStadium" ("StadiumStatusCode");

CREATE INDEX IF NOT EXISTS "IX_MstStadium_StadiumTypeCode" ON "MstStadium" ("StadiumTypeCode");

CREATE INDEX IF NOT EXISTS "IX_MstStadiumFileModel_StadiumCode" ON "MstStadiumFileModel" ("StadiumCode");

CREATE INDEX IF NOT EXISTS "IX_MstTenantContact_TenantId" ON "MstTenantContact" ("TenantId");

CREATE INDEX IF NOT EXISTS "IX_News_CategoryNewsId" ON "News" ("CategoryNewsId");

CREATE INDEX IF NOT EXISTS "IX_News_UserId" ON "News" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_NewsComment_NewsId" ON "NewsComment" ("NewsId");

CREATE INDEX IF NOT EXISTS "IX_NewsComment_ParentCommentId" ON "NewsComment" ("ParentCommentId");

CREATE INDEX IF NOT EXISTS "IX_NewsComment_UserId" ON "NewsComment" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_NewsCommentMedia_CommentId" ON "NewsCommentMedia" ("CommentId");

CREATE INDEX IF NOT EXISTS "IX_NewsCommentReaction_UserId" ON "NewsCommentReaction" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_NewsReportComment_CommentId" ON "NewsReportComment" ("CommentId");

CREATE INDEX IF NOT EXISTS "IX_NewsReportComment_UserId" ON "NewsReportComment" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_OrderStadium_PaymentTypeCode" ON "OrderStadium" ("PaymentTypeCode");

CREATE INDEX IF NOT EXISTS "IX_OrderStadium_StadiumCode" ON "OrderStadium" ("StadiumCode");

CREATE INDEX IF NOT EXISTS "IX_OrderStadium_UserId" ON "OrderStadium" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_OrderStadiumStatusLogModel_OrderStadiumId" ON "OrderStadiumStatusLogModel" ("OrderStadiumId");

CREATE INDEX IF NOT EXISTS "IX_OrderStadiumStatusLogModel_UserId" ON "OrderStadiumStatusLogModel" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_PointNews_UserId" ON "PointNews" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_RefFileNews_NewsId" ON "RefFileNews" ("NewsId");

CREATE INDEX IF NOT EXISTS "IX_RefreshToken_UserId" ON "RefreshToken" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_ShiftReport_ReceptionistName" ON "ShiftReport" ("ReceptionistName");

CREATE INDEX IF NOT EXISTS "IX_ShiftReport_ShiftDate" ON "ShiftReport" ("ShiftDate");

CREATE INDEX IF NOT EXISTS "IX_ShiftReportRoomSale_ShiftReportId" ON "ShiftReportRoomSale" ("ShiftReportId");

CREATE INDEX IF NOT EXISTS "IX_ShiftReportTransaction_ShiftReportId" ON "ShiftReportTransaction" ("ShiftReportId");
