CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "TenantId" integer NOT NULL,
    "FullName" text,
    "Avatar" text,
    "Address" text,
    "FlagActive" boolean NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Chat" (
    "MessageId" text NOT NULL,
    "UserId" text NOT NULL,
    "Type" text NOT NULL,
    "Message" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Chat" PRIMARY KEY ("MessageId")
);

CREATE TABLE "MstPaymentTypes" (
    "PaymentTypeCode" text NOT NULL,
    "PaymentTypeName" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstPaymentTypes" PRIMARY KEY ("PaymentTypeCode")
);

CREATE TABLE "MstProvinces" (
    "ProvinceCode" character varying(10) NOT NULL,
    "ProvinceName" text NOT NULL,
    "TenantId" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstProvinces" PRIMARY KEY ("ProvinceCode")
);

CREATE TABLE "MstStadiumStatuses" (
    "StadiumStatusCode" text NOT NULL,
    "StadiumStatusName" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstStadiumStatuses" PRIMARY KEY ("StadiumStatusCode")
);

CREATE TABLE "MstStadiumTypes" (
    "StadiumTypeCode" text NOT NULL,
    "StadiumTypeName" text NOT NULL,
    "StadiumTypeSalePercent" numeric NOT NULL,
    "Remark" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstStadiumTypes" PRIMARY KEY ("StadiumTypeCode")
);

CREATE TABLE "NewsCategory" (
    "NewsCategoryId" text NOT NULL,
    "TenantId" text NOT NULL,
    "NewsCategoryParentId" text NOT NULL,
    "NewsCategoryName" text NOT NULL,
    "NewsCategoryIndex" integer NOT NULL,
    "IsGlobal" boolean NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NewsCategory" PRIMARY KEY ("NewsCategoryId")
);

CREATE TABLE "Tenants" (
    "TenantId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantCode" text NOT NULL,
    "TenantName" text NOT NULL,
    "OwnedBy" text NOT NULL,
    "TenantPrefixHost" text NOT NULL,
    "TenantHost" text NOT NULL,
    "TenantConnectionString" text NOT NULL,
    "TenantDatabaseName" text NOT NULL,
    "TenantLogo" text NOT NULL,
    "TenantDescription" text NOT NULL,
    "TenantAddress" jsonb NOT NULL,
    "TenantStatus" varchar(20) NOT NULL,
    "Remark" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("TenantId")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshTokens" (
    "RefreshToken" text NOT NULL,
    "TenantId" text NOT NULL,
    "UserId" text NOT NULL,
    "ExpiryDate" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("RefreshToken"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "MstDistricts" (
    "DistrictCode" text NOT NULL,
    "ProvinceCode" character varying(10) NOT NULL,
    "DistrictName" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstDistricts" PRIMARY KEY ("DistrictCode"),
    CONSTRAINT "FK_MstDistricts_MstProvinces_ProvinceCode" FOREIGN KEY ("ProvinceCode") REFERENCES "MstProvinces" ("ProvinceCode") ON DELETE RESTRICT
);

CREATE TABLE "News" (
    "NewsId" text NOT NULL,
    "UserId" text NOT NULL,
    "CategoryNewsId" text NOT NULL,
    "Slug" text NOT NULL,
    "Thumbnail" text NOT NULL,
    "ShortTitle" text NOT NULL,
    "ShortDescription" text NOT NULL,
    "ContentBody" text NOT NULL,
    "ViewCount" integer NOT NULL,
    "ShareCount" integer NOT NULL,
    "LikeCount" integer NOT NULL,
    "AvgPoint" double precision NOT NULL,
    "WhoCanSee" varchar(20) NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_News" PRIMARY KEY ("NewsId"),
    CONSTRAINT "FK_News_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_News_NewsCategory_CategoryNewsId" FOREIGN KEY ("CategoryNewsId") REFERENCES "NewsCategory" ("NewsCategoryId") ON DELETE CASCADE
);

CREATE TABLE "MstTenantContacts" (
    "TenantContactId" text NOT NULL,
    "TenantId" integer NOT NULL,
    "TenantContactName" varchar(20) NOT NULL,
    "TenantContactValue" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstTenantContacts" PRIMARY KEY ("TenantContactId"),
    CONSTRAINT "FK_MstTenantContacts_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("TenantId") ON DELETE CASCADE
);

CREATE TABLE "MstStadiums" (
    "StadiumCode" character varying(250) NOT NULL,
    "StadiumTypeCode" text NOT NULL,
    "StadiumStatusCode" text NOT NULL,
    "DistrictCode" text NOT NULL,
    "TenantId" text NOT NULL,
    "FlagStadiumRent" boolean NOT NULL,
    "StadiumName" text NOT NULL,
    "StadiumPrice" numeric NOT NULL,
    "StadiumDescription" text NOT NULL,
    "StadiumAddress" text NOT NULL,
    "StadiumSalePercent" numeric NOT NULL,
    "Remark" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstStadiums" PRIMARY KEY ("StadiumCode"),
    CONSTRAINT "FK_MstStadiums_MstDistricts_DistrictCode" FOREIGN KEY ("DistrictCode") REFERENCES "MstDistricts" ("DistrictCode") ON DELETE CASCADE,
    CONSTRAINT "FK_MstStadiums_MstStadiumStatuses_StadiumStatusCode" FOREIGN KEY ("StadiumStatusCode") REFERENCES "MstStadiumStatuses" ("StadiumStatusCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_MstStadiums_MstStadiumTypes_StadiumTypeCode" FOREIGN KEY ("StadiumTypeCode") REFERENCES "MstStadiumTypes" ("StadiumTypeCode") ON DELETE RESTRICT
);

CREATE TABLE "HashTagNews" (
    "HashTagNewsId" text NOT NULL,
    "NewsId" text NOT NULL,
    "HashTagNewsName" character varying(30) NOT NULL,
    "Count" integer NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HashTagNews" PRIMARY KEY ("HashTagNewsId", "NewsId"),
    CONSTRAINT "FK_HashTagNews_News_NewsId" FOREIGN KEY ("NewsId") REFERENCES "News" ("NewsId") ON DELETE CASCADE
);

CREATE TABLE "LikeNews" (
    "LikeNewsId" text NOT NULL,
    "NewsId" text NOT NULL,
    "UserId" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LikeNews" PRIMARY KEY ("LikeNewsId"),
    CONSTRAINT "FK_LikeNews_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LikeNews_News_NewsId" FOREIGN KEY ("NewsId") REFERENCES "News" ("NewsId") ON DELETE CASCADE
);

CREATE TABLE "PointNews" (
    "NewsId" text NOT NULL,
    "UserId" text NOT NULL,
    "Point" double precision NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PointNews" PRIMARY KEY ("NewsId", "UserId"),
    CONSTRAINT "FK_PointNews_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PointNews_News_NewsId" FOREIGN KEY ("NewsId") REFERENCES "News" ("NewsId") ON DELETE CASCADE
);

CREATE TABLE "RefFileNews" (
    "RefFileNewsId" text NOT NULL,
    "NewsId" text NOT NULL,
    "FileUrl" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefFileNews" PRIMARY KEY ("RefFileNewsId"),
    CONSTRAINT "FK_RefFileNews_News_NewsId" FOREIGN KEY ("NewsId") REFERENCES "News" ("NewsId") ON DELETE CASCADE
);

CREATE TABLE "MstStadiumFileModel" (
    "StadiumFileId" text NOT NULL,
    "StadiumCode" character varying(250) NOT NULL,
    "FileUrl" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MstStadiumFileModel" PRIMARY KEY ("StadiumFileId"),
    CONSTRAINT "FK_MstStadiumFileModel_MstStadiums_StadiumCode" FOREIGN KEY ("StadiumCode") REFERENCES "MstStadiums" ("StadiumCode") ON DELETE CASCADE
);

CREATE TABLE "OrderStadiums" (
    "OrderStadiumId" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderStadiumCode" text NOT NULL,
    "StadiumCode" character varying(250) NOT NULL,
    "UserId" text NOT NULL,
    "OderDTime" timestamp with time zone NOT NULL,
    "RentDTimeFrom" timestamp with time zone NOT NULL,
    "RentDTimeTo" timestamp with time zone NOT NULL,
    "PaymentTypeCode" text NOT NULL,
    "PreMoney" numeric NOT NULL,
    "RefundMoney" numeric NOT NULL,
    "SalePercent" numeric NOT NULL,
    "DebtMoney" numeric NOT NULL,
    "Remark" text NOT NULL,
    "OrderStatus" varchar(20) NOT NULL,
    "VoucherCode" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OrderStadiums" PRIMARY KEY ("OrderStadiumId"),
    CONSTRAINT "FK_OrderStadiums_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderStadiums_MstPaymentTypes_PaymentTypeCode" FOREIGN KEY ("PaymentTypeCode") REFERENCES "MstPaymentTypes" ("PaymentTypeCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderStadiums_MstStadiums_StadiumCode" FOREIGN KEY ("StadiumCode") REFERENCES "MstStadiums" ("StadiumCode") ON DELETE RESTRICT
);

CREATE TABLE "OrderStadiumStatusLogModel" (
    "OrderStadiumStatusLogId" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderStadiumId" integer NOT NULL,
    "UserId" text NOT NULL,
    "PreviousStatus" text NOT NULL,
    "Status" text NOT NULL,
    "ChangedData" text NOT NULL,
    "Note" text NOT NULL,
    "IpAddress" text NOT NULL,
    "FlagActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text NOT NULL,
    "CreatedDTime" timestamp with time zone NOT NULL,
    "UpdatedDTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OrderStadiumStatusLogModel" PRIMARY KEY ("OrderStadiumStatusLogId"),
    CONSTRAINT "FK_OrderStadiumStatusLogModel_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderStadiumStatusLogModel_OrderStadiums_OrderStadiumId" FOREIGN KEY ("OrderStadiumId") REFERENCES "OrderStadiums" ("OrderStadiumId") ON DELETE RESTRICT
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_HashTagNews_NewsId" ON "HashTagNews" ("NewsId");

CREATE INDEX "IX_LikeNews_NewsId" ON "LikeNews" ("NewsId");

CREATE INDEX "IX_LikeNews_UserId" ON "LikeNews" ("UserId");

CREATE INDEX "IX_MstDistricts_ProvinceCode" ON "MstDistricts" ("ProvinceCode");

CREATE INDEX "IX_MstStadiumFileModel_StadiumCode" ON "MstStadiumFileModel" ("StadiumCode");

CREATE INDEX "IX_MstStadiums_DistrictCode" ON "MstStadiums" ("DistrictCode");

CREATE INDEX "IX_MstStadiums_StadiumStatusCode" ON "MstStadiums" ("StadiumStatusCode");

CREATE INDEX "IX_MstStadiums_StadiumTypeCode" ON "MstStadiums" ("StadiumTypeCode");

CREATE INDEX "IX_MstTenantContacts_TenantId" ON "MstTenantContacts" ("TenantId");

CREATE INDEX "IX_News_CategoryNewsId" ON "News" ("CategoryNewsId");

CREATE INDEX "IX_News_UserId" ON "News" ("UserId");

CREATE INDEX "IX_OrderStadiums_PaymentTypeCode" ON "OrderStadiums" ("PaymentTypeCode");

CREATE INDEX "IX_OrderStadiums_StadiumCode" ON "OrderStadiums" ("StadiumCode");

CREATE INDEX "IX_OrderStadiums_UserId" ON "OrderStadiums" ("UserId");

CREATE INDEX "IX_OrderStadiumStatusLogModel_OrderStadiumId" ON "OrderStadiumStatusLogModel" ("OrderStadiumId");

CREATE INDEX "IX_OrderStadiumStatusLogModel_UserId" ON "OrderStadiumStatusLogModel" ("UserId");

CREATE INDEX "IX_PointNews_UserId" ON "PointNews" ("UserId");

CREATE INDEX "IX_RefFileNews_NewsId" ON "RefFileNews" ("NewsId");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250707164726_InitialClean', '8.0.2');

COMMIT;

